-- Add missing columns to movies table
ALTER TABLE movies
ADD COLUMN IF NOT EXISTS tmdb_id INTEGER,
ADD COLUMN IF NOT EXISTS media_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS year INTEGER,
ADD COLUMN IF NOT EXISTS poster_url TEXT,
ADD COLUMN IF NOT EXISTS director VARCHAR(255),
ADD COLUMN IF NOT EXISTS actor VARCHAR(255),
ADD COLUMN IF NOT EXISTS genre VARCHAR(255);
